### ISSUE TITLE
⭐️ Feature: 환경변수 치환

### ISSUE THREAD

**Issue by nyj001012** [chanheki/minishell#16]
### Context
 - 토큰화 전 또는 후에 환경변수 치환
 - 큰 따옴표 안에 싸여있는 경우
 - 어떠한 따옴표에도 싸여있지 않은 경우
 - <, >, <<, >>의 파일 명이 아닌 경우

### Tasks
- [x] 큰 따옴표 안에 싸여있는 경우, 환경변수로 치환
- [x] 어떠한 따옴표에도 싸여있지 않은 경우, 환경변수로 치환
- [ ] <, >, <<, >>의 파일 명인 경우, 환경변수로 치환하지 않음

### Files
 -
