### ISSUE TITLE
👕 Refactor: 파싱부 리팩터링

### ISSUE THREAD

**Issue by nyj001012** [chanheki/minishell#28]
### Context
 - 파싱부 리팩터링

### Tasks
- [x] 파일 주소 변경 `parse/wildcard/*.c` -> `parse/token/*.c`
- [x] 파일 주소 변경 `parse/expansion/*.c` -> `parse/token/*.c`
- [x] libft 삭제
- [x] `s_ASTnode`의 `type` 및 `e_node_type` 삭제
- [x] `e_token_status` 삭제
- [x] `parse.h` 헤더 내 COMMAND_SPLIT 정의 삭제
- [x] 따옴표인지 확인하는 로직 함수로 추출
- [x] 주석 오타 수정

### Files
 - `parse/**/*.c`
 - `include/parse.h`
