### ISSUE TITLE
⭐️ Feature: excute draft

### ISSUE THREAD

**Issue by chanhihi** [chanheki/minishell#50]
### Context
 - 만들어진 parsing tree를 토대로 excute의 의사코드 및 draft를 작성합니다.

### Tasks
- [ ] parse tree를 토대로 실행할 excute list에 관한 draft
- [ ] 재귀로 구현할 지 다시 재 검토
- [ ] 실행부 세부 구현사항 의사코드 작성

### Files
 -
